### PR TITLE
Fix flaky test due to too short timeout

### PR DESCRIPTION
**Pull request by itholic**
This PR proposes to fix flaky test `testShutdownSubprocessThatDiesOnExit`.

The current timeout waiting for shutting down callback server is 0.3125 (2**-5), but seems it's not enough so the test is often failed due to `TimeoutExpired` exception.

Increasing the waiting time to 1 sec may fix the flakiness.

Refer to https://github.com/py4j/py4j/pull/463#issuecomment-1054080032 and https://github.com/py4j/py4j/runs/5389683418?check_suite_focus=true for more detail.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@itholic seems like the test is still flaky:

```
======================================================================
ERROR: testShutdownSubprocessThatDiesOnExit (py4j.tests.java_gateway_test.GatewayLauncherTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/py4j/py4j/py4j-python/src/py4j/tests/java_gateway_test.py", line 1073, in testShutdownSubprocessThatDiesOnExit
    self.gateway.java_process.wait(2**-5)
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/subprocess.py", line 1391, in wait
    raise TimeoutExpired(self.args, timeout)
subprocess.TimeoutExpired: Command '['java', '-classpath', '/home/runner/work/py4j/py4j/py4j-python/src/py4j/../../../py4j-java/py4j0.10.9.3.jar:', 'py4j.GatewayServer', '--die-on-broken-pipe', '0']' timed out after 0.03125 seconds
-------------------- >> begin captured logging << --------------------
py4j.java_gateway: DEBUG: Launching gateway with command ['java', '-classpath', '/home/runner/work/py4j/py4j/py4j-python/src/py4j/../../../py4j-java/py4j0.10.9.3.jar:', 'py4j.GatewayServer', '--die-on-broken-pipe', '0']
py4j.java_gateway: DEBUG: Exception while shutting down a socket
Traceback (most recent call last):
  File "/home/runner/work/py4j/py4j/py4j-python/src/py4j/java_gateway.py", line 503, in quiet_shutdown
    socket_instance.shutdown(socket.SHUT_RDWR)
OSError: [Errno 9] Bad file descriptor
py4j.java_gateway: INFO: Exception while shutting down callback server
Traceback (most recent call last):
  File "/home/runner/work/py4j/py4j/py4j-python/src/py4j/java_gateway.py", line 1983, in shutdown
    self._gateway_client.shutdown_gateway()
  File "/home/runner/work/py4j/py4j/py4j-python/src/py4j/java_gateway.py", line 1006, in shutdown_gateway
    connection = self._get_connection()
  File "/home/runner/work/py4j/py4j/py4j-python/src/py4j/java_gateway.py", line 980, in _get_connection
    raise Py4JNetworkError("Gateway is not connected.")
py4j.protocol.Py4JNetworkError: Gateway is not connected.
--------------------- >> end captured logging << ---------------------
```

**Comment by itholic** [comment]
During fixing `testShutdownSubprocessThatDiesOnExit`, another exception is occurred from `MemoryManagementTest` as below:

```
Traceback (most recent call last):
  File "/home/runner/work/py4j/py4j/py4j-python/src/py4j/tests/java_gateway_test.py", line 535, in testNoAttach
    Exception, lambda: gateway2.jvm.java.lang.StringBuffer())
AssertionError: Exception not raised by <lambda>
-------------------- >> begin captured logging << --------------------
py4j.java_gateway: DEBUG: Command to send: r
u
Traceback (most recent call last):
  File "/home/runner/work/py4j/py4j/py4j-python/src/py4j/java_gateway.py", line 1217, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/socket.py", line [576](https://github.com/py4j/py4j/runs/5455795939?check_suite_focus=true#step:10:576), in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
py4j.java_gateway: DEBUG: Exception while shutting down a socket
Traceback (most recent call last):
  File "/home/runner/work/py4j/py4j/py4j-python/src/py4j/java_gateway.py", line 1217, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/py4j/py4j/py4j-python/src/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/runner/work/py4j/py4j/py4j-python/src/py4j/java_gateway.py", line 1229, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/py4j/py4j/py4j-python/src/py4j/java_gateway.py", line 503, in quiet_shutdown
    socket_instance.shutdown(socket.SHUT_RDWR)
OSError: [Errno 107] Transport endpoint is not connected
root: ERROR: Exception while sending command.
Traceback (most recent call last):
  File "/home/runner/work/py4j/py4j/py4j-python/src/py4j/java_gateway.py", line 1217, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/py4j/py4j/py4j-python/src/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/runner/work/py4j/py4j/py4j-python/src/py4j/java_gateway.py", line 1229, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving
py4j.java_gateway: DEBUG: Exception while shutting down a socket
Traceback (most recent call last):
  File "/home/runner/work/py4j/py4j/py4j-python/src/py4j/java_gateway.py", line 503, in quiet_shutdown
    socket_instance.shutdown(socket.SHUT_RDWR)
OSError: [Errno 9] Bad file descriptor
py4j.java_gateway: INFO: Exception while shutting down callback server
Traceback (most recent call last):
  File "/home/runner/work/py4j/py4j/py4j-python/src/py4j/java_gateway.py", line 1983, in shutdown
    self._gateway_client.shutdown_gateway()
  File "/home/runner/work/py4j/py4j/py4j-python/src/py4j/java_gateway.py", line 1006, in shutdown_gateway
    connection = self._get_connection()
  File "/home/runner/work/py4j/py4j/py4j-python/src/py4j/java_gateway.py", line 980, in _get_connection
    raise Py4JNetworkError("Gateway is not connected.")
py4j.protocol.Py4JNetworkError: Gateway is not connected.
```

I'm investigation to solve this now.

**Comment by HyukjinKwon** [comment]
@itholic mind running multiple times, and confirm that it fixes the flakiness?

**Comment by itholic** [comment]
Ran 8 times: 6 succeeded, 2 manually canceling since it's pending longtime for some reason.

I'm not sure why the test sometimes pending longtime, buu I think at least the flakiness due to TimeoutExpired is resolved.

**Review by HyukjinKwon — APPROVED** [review]

**Pull request merged**
