### PR TITLE
Add support for Java 17

### PR DESCRIPTION
**Pull request by torokati44**
This tries to address #403 and a few related issues, by implementing Option 3 from https://github.com/bartdag/py4j/issues/403#issuecomment-782728385.

Unfortunately(?) this raises the minimum JDK version to 9.
I agree that it's not possible to properly solve this, while also supporting both Java 8 and Java 17, with a single build.

I also gave Option 1 a try, but that way not even `getCallbackClient()` was accessible, so I didn't pursue it further.

### CODE REVIEW

**Comment by tueda** [comment]
If it works only with JDK 9+, then should `sourceCompatibility` and `targetCompatibility` be changed to `9`? I find them in `py4j-java/gradle.properties` and `py4j-java/build.gradle`.

**Comment by torokati44** [comment]
I suppose...

**Comment by JoshRosen** [comment]
Apache Spark relies on Py4J and (as of now) has not announced plans to drop Java 8 support.

I'm wondering if we can retain Java 8 support by using either reflection or MethodHandles to use `trySetAccessible` only if it's available and continue running the existing code on Java 8. This idea is inspired by a similar proposal in `lz4-java` to use MethodHandles to use Java 9+ features if available without having to rely on multi-version JARs: https://github.com/lz4/lz4-java/issues/183

**Comment by cozek** [comment]
Hi, any updates regarding this?

**Comment by HyukjinKwon** [comment]
I will work on this soon - probably in the next quarter.

**Comment by HyukjinKwon** [comment]
Hey guys, we plan to work on it in this quarter. I will leave it closed this as a duplicate of https://github.com/py4j/py4j/issues/485. Let's track it there.

**Pull request closed without merging**
