### PR TITLE
Bump license ending year to 2022

### PR DESCRIPTION
**Pull request by zhongjiajie**
ATT, this patch bump license to year 2022

### CODE REVIEW

**Comment by zhongjiajie** [comment]
Hi @HyukjinKwon, I find out we prepare the new release, we should consider this License issue, WDYT?

**Comment by HyukjinKwon** [comment]
Yeah, should it be 2022 btw?

**Comment by zhongjiajie** [comment]
I update it later

**Comment by zhongjiajie** [comment]
I update to a year to 2022, this PR submit in 2021 and I do not change it until you mention that, PTAL @HyukjinKwon thanks

**Review by HyukjinKwon — APPROVED** [review]
I think this is fine. but would need a confirmation from @bartdag for sure.

**Comment by bartdag** [comment]
It's fine, thanks!

For your information, if you change py4j.license.java and run gradle spotlessApply, it will change the header of all java files. See https://github.com/py4j/py4j/blob/master/py4j-java/build.gradle#L110

**Review by bartdag — APPROVED** [review]
I approve, many thanks!!

**Comment by zhongjiajie** [comment]
> It's fine, thanks!
> 
> For your information, if you change py4j.license.java and run gradle spotlessApply, it will change the header of all java files. See https://github.com/py4j/py4j/blob/master/py4j-java/build.gradle#L110

Thanks, it is helpful, in this PR I batch replace in IDEA to do this

**Comment by HyukjinKwon** [comment]
Merged.

**Comment by zhongjiajie** [comment]
Thanks

**Pull request merged**
